'use client';

import React from 'react';
import {
    HomeIcon,
    AcademicCapIcon,
    CurrencyDollarIcon,
    UserCircleIcon,
    Cog6ToothIcon,
    EllipsisHorizontalIcon,
    XMarkIcon,
    Bars3Icon,
    ClockIcon,
    HeartIcon,
    FunnelIcon,
    QuestionMarkCircleIcon,
    CheckCircleIcon,
    ExclamationCircleIcon,
    InformationCircleIcon,
    ArrowRightIcon,
    ArrowLeftIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    ChevronRightIcon,
    ChevronLeftIcon,
    MagnifyingGlassIcon,
    PlusIcon,
    MinusIcon,
    PencilIcon,
    TrashIcon,
    DocumentIcon,
    FolderIcon,
    PhotoIcon,
    VideoCameraIcon,
    MusicalNoteIcon,
    GlobeAltIcon,
    LinkIcon,
    ShareIcon,
    BookmarkIcon,
    StarIcon,
    BellIcon,
    EnvelopeIcon,
    ChatBubbleLeftIcon,
    PhoneIcon,
    MapPinIcon,
    CalendarIcon,
    ClipboardIcon,
    DocumentDuplicateIcon,
    ArrowDownTrayIcon,
    ArrowUpTrayIcon,
    ArrowPathIcon,
    EyeIcon,
    EyeSlashIcon,
    LockClosedIcon,
    LockOpenIcon,
    ShieldCheckIcon,
    KeyIcon,
    CreditCardIcon,
    BanknotesIcon,
    BuildingLibraryIcon,
    ShoppingCartIcon,
    ShoppingBagIcon,
    GiftIcon,
    TrophyIcon,
    SparklesIcon,
    FireIcon,
    BoltIcon,
    SunIcon,
    MoonIcon,
    ComputerDesktopIcon,
    DevicePhoneMobileIcon,
    WifiIcon,
    SignalIcon,
    CpuChipIcon,
    ServerIcon,
    CloudIcon,
    CodeBracketIcon,
    CommandLineIcon,
    CubeIcon,
    RocketLaunchIcon,
    AdjustmentsHorizontalIcon,
    Squares2X2Icon,
    ListBulletIcon,
    TableCellsIcon,
    ChartBarIcon,
    ChartPieIcon,
    PresentationChartLineIcon,
    UserGroupIcon,
    UsersIcon,
    UserPlusIcon,
    UserMinusIcon,
    IdentificationIcon,
    FingerPrintIcon,
    HandThumbUpIcon,
    HandThumbDownIcon,
    FaceSmileIcon,
    FaceFrownIcon,
    ChatBubbleOvalLeftEllipsisIcon,
    PaperAirplaneIcon,
    InboxIcon,
    ArchiveBoxIcon,
    FlagIcon,
    TagIcon,
    HashtagIcon,
    AtSymbolIcon,
    LanguageIcon,
    PrinterIcon,
    ScissorsIcon,
    PaperClipIcon,
    BookOpenIcon,
    NewspaperIcon,
    MegaphoneIcon,
    SpeakerWaveIcon,
    SpeakerXMarkIcon,
    PlayIcon,
    PauseIcon,
    StopIcon,
    ForwardIcon,
    BackwardIcon,
    WindowIcon,
    SwatchIcon,
    PaintBrushIcon,
    BeakerIcon,
    WrenchIcon,
    WrenchScrewdriverIcon,
    CogIcon,
    BuildingOfficeIcon,
    BuildingOffice2Icon,
    HomeModernIcon,
    BuildingStorefrontIcon,
    TruckIcon,
    PaperClipIcon as AttachIcon,
} from '@heroicons/react/24/outline';

import {
    HeartIcon as HeartSolid,
    StarIcon as StarSolid,
    BookmarkIcon as BookmarkSolid,
    BellIcon as BellSolid,
    CheckCircleIcon as CheckCircleSolid,
    ExclamationCircleIcon as ExclamationCircleSolid,
    HomeIcon as HomeSolid,
    UserCircleIcon as UserCircleSolid,
} from '@heroicons/react/24/solid';

// Map icon names to components - only load what's used
const outlineIcons: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
    HomeIcon,
    AcademicCapIcon,
    CurrencyDollarIcon,
    UserCircleIcon,
    Cog6ToothIcon,
    EllipsisHorizontalIcon,
    XMarkIcon,
    Bars3Icon,
    ClockIcon,
    HeartIcon,
    FunnelIcon,
    QuestionMarkCircleIcon,
    CheckCircleIcon,
    ExclamationCircleIcon,
    InformationCircleIcon,
    ArrowRightIcon,
    ArrowLeftIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    ChevronRightIcon,
    ChevronLeftIcon,
    MagnifyingGlassIcon,
    PlusIcon,
    MinusIcon,
    PencilIcon,
    TrashIcon,
    DocumentIcon,
    FolderIcon,
    PhotoIcon,
    VideoCameraIcon,
    MusicalNoteIcon,
    GlobeAltIcon,
    LinkIcon,
    ShareIcon,
    BookmarkIcon,
    StarIcon,
    BellIcon,
    EnvelopeIcon,
    ChatBubbleLeftIcon,
    PhoneIcon,
    MapPinIcon,
    CalendarIcon,
    ClipboardIcon,
    DocumentDuplicateIcon,
    ArrowDownTrayIcon,
    ArrowUpTrayIcon,
    ArrowPathIcon,
    EyeIcon,
    EyeSlashIcon,
    LockClosedIcon,
    LockOpenIcon,
    ShieldCheckIcon,
    KeyIcon,
    CreditCardIcon,
    BanknotesIcon,
    BuildingLibraryIcon,
    ShoppingCartIcon,
    ShoppingBagIcon,
    GiftIcon,
    TrophyIcon,
    SparklesIcon,
    FireIcon,
    BoltIcon,
    SunIcon,
    MoonIcon,
    ComputerDesktopIcon,
    DevicePhoneMobileIcon,
    WifiIcon,
    SignalIcon,
    CpuChipIcon,
    ServerIcon,
    CloudIcon,
    CodeBracketIcon,
    CommandLineIcon,
    CubeIcon,
    RocketLaunchIcon,
    AdjustmentsHorizontalIcon,
    Squares2X2Icon,
    ListBulletIcon,
    TableCellsIcon,
    ChartBarIcon,
    ChartPieIcon,
    PresentationChartLineIcon,
    UserGroupIcon,
    UsersIcon,
    UserPlusIcon,
    UserMinusIcon,
    IdentificationIcon,
    FingerPrintIcon,
    HandThumbUpIcon,
    HandThumbDownIcon,
    FaceSmileIcon,
    FaceFrownIcon,
    ChatBubbleOvalLeftEllipsisIcon,
    PaperAirplaneIcon,
    InboxIcon,
    ArchiveBoxIcon,
    FlagIcon,
    TagIcon,
    HashtagIcon,
    AtSymbolIcon,
    LanguageIcon,
    PrinterIcon,
    ScissorsIcon,
    PaperClipIcon,
    BookOpenIcon,
    NewspaperIcon,
    MegaphoneIcon,
    SpeakerWaveIcon,
    SpeakerXMarkIcon,
    PlayIcon,
    PauseIcon,
    StopIcon,
    ForwardIcon,
    BackwardIcon,
    WindowIcon,
    SwatchIcon,
    PaintBrushIcon,
    BeakerIcon,
    WrenchIcon,
    WrenchScrewdriverIcon,
    CogIcon,
    BuildingOfficeIcon,
    BuildingOffice2Icon,
    HomeModernIcon,
    BuildingStorefrontIcon,
    TruckIcon,
    AttachIcon,
};

const solidIcons: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
    HeartIcon: HeartSolid,
    StarIcon: StarSolid,
    BookmarkIcon: BookmarkSolid,
    BellIcon: BellSolid,
    CheckCircleIcon: CheckCircleSolid,
    ExclamationCircleIcon: ExclamationCircleSolid,
    HomeIcon: HomeSolid,
    UserCircleIcon: UserCircleSolid,
};

type IconVariant = 'outline' | 'solid';

interface IconProps {
    name: string;
    variant?: IconVariant;
    size?: number;
    className?: string;
    onClick?: () => void;
    disabled?: boolean;
    [key: string]: unknown;
}

function Icon({
    name,
    variant = 'outline',
    size = 24,
    className = '',
    onClick,
    disabled = false,
    ...props
}: IconProps) {
    const iconSet = variant === 'solid' ? solidIcons : outlineIcons;
    const IconComponent = iconSet[name];

    if (!IconComponent) {
        return (
            <QuestionMarkCircleIcon
                width={size}
                height={size}
                className={`text-gray-400 ${disabled ? 'opacity-50 cursor-not-allowed' : ''} ${className}`}
                onClick={disabled ? undefined : onClick}
                {...props}
            />
        );
    }

    return (
        <IconComponent
            width={size}
            height={size}
            className={`${disabled ? 'opacity-50 cursor-not-allowed' : onClick ? 'cursor-pointer hover:opacity-80' : ''} ${className}`}
            onClick={disabled ? undefined : onClick}
            {...props}
        />
    );
}

export default Icon;